import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import http from 'node:http';
import { once } from 'node:events';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
test('Node HTTP keeps full target validation and rejects TRACE/POST without crashing',async t=>{
  const directory=await mkdtemp(path.join(tmpdir(),'homecall-catalog-test-'));
  const catalogPath=path.join(directory,'catalog.json');
  await writeFile(catalogPath,JSON.stringify({schemaVersion:1,version:'test',updatedAt:'2026-09-01T00:00:00Z',live:{fixture:{url:'https://audio.example/live',allowedOrigins:['https://audio.example'],kind:'audio'}},archive:{checkedAt:'2026-09-01T00:00:00Z',schools:{}}}));
  t.after(()=>rm(directory,{recursive:true,force:true}));
  const child=spawn(process.execPath,['server.mjs'],{env:{...process.env,PORT:'0',HOMECALL_CATALOG_FILE:catalogPath},stdio:['ignore','pipe','pipe']});
  t.after(async()=>{if(child.exitCode===null && child.signalCode===null){const exited=once(child,'exit');child.kill('SIGTERM');await exited;}});
  const url=await new Promise((resolve,reject)=>{let output='';const timeout=setTimeout(()=>reject(Error('Server startup timed out')),5000);child.once('exit',()=>clearTimeout(timeout));child.stdout.on('data',chunk=>{output+=chunk;const match=output.match(/http:\/\/127\.0\.0\.1:\d+/);if(match){clearTimeout(timeout);resolve(match[0]);}});child.on('error',reject);child.on('exit',code=>reject(Error('Server exited '+code)));});
  const request=(path,method='GET')=>new Promise((resolve,reject)=>{const req=http.request(url+path,{method},response=>{response.resume();response.on('end',()=>resolve(response.statusCode));});req.on('error',reject);req.end(method==='POST'?'ignored body':undefined);});
  assert.equal(await request('/api/sync/teams','TRACE'),405);
  assert.equal(await request('/api/sync/teams','POST'),405);
  assert.equal(await request('/api/sync/teams?host=evil'),404);
  assert.equal(await request('/api/sync/%74eams'),404);
  assert.equal(await request('/api/sync/plays/1?event=2'),404);
  assert.equal(await request('/api/sync/missing'),404);
  const projected=await (await fetch(url+'/api/catalog/live')).json();
  assert.equal(projected[0].id,'fixture');assert.equal(new URL(projected[0].url).pathname,'/media/live/fixture');
  assert.ok(!JSON.stringify(projected).includes('audio.example'));
  assert.equal(await request('/media/live/unknown'),404);
  assert.equal(await request('/media/live/fixture?url=https://evil.example'),404);
});
