import test from 'node:test';
import assert from 'node:assert/strict';
import {readPrivateCatalog,publicArchiveCatalog,publicLiveCatalog,findArchiveTarget,refreshPrivateCatalog} from '../lib/private-catalog.mjs';
const stamp='2026-09-01T00:00:00.000Z';
const seed=()=>({schemaVersion:1,version:'1',updatedAt:stamp,live:{duke:{url:'https://audio.example/live',allowedOrigins:['https://audio.example'],kind:'audio'}},archive:{checkedAt:stamp,schools:{duke:{source:'https://school.example/',status:'ready',checkedAt:stamp,items:[{id:'a',opponent:'Visitor',sport:'Football',start:stamp,url:'https://audio.example/replay/123.mp3',kind:'Game recording'}]},vt:{source:'https://school.example/vt',status:'unavailable',items:[]}}},archiveConfig:{dukePlayer:'https://player.example/',dukeFeedPath:'/previous.xml',vtFeed:'https://feed.example/vt',replayRules:{duke:[{origin:'https://audio.example',pathPrefix:'/replay/',filenamePattern:'^\\d+\\.mp3$'}],vt:[]}}});
function storage(value){let current=JSON.stringify(value);const writes=[];return {env:{STREAM_CATALOG:{get:async()=>current,put:async(k,v)=>{writes.push([k,v]);current=v;}}},writes,get:()=>JSON.parse(current)};}
test('public projection exposes gateway addresses and no private fields',async()=>{const {env}=storage(seed());const c=await readPrivateCatalog(env);const output=JSON.stringify([publicArchiveCatalog(c,'https://gateway.example'),publicLiveCatalog(c,'https://gateway.example')]);assert.ok(!output.includes('audio.example'));assert.ok(!output.includes('archiveConfig'));assert.match(output,/media\/archive\/duke\/a/);assert.equal(findArchiveTarget(c,'duke','a').url,c.archive.schools.duke.items[0].url);assert.equal(findArchiveTarget(c,'duke','missing'),null);});
test('failed refresh preserves recordings and their last successful timestamp',async()=>{const s=storage(seed());await refreshPrivateCatalog(s.env,{fetcher:async()=>{throw Error('private URL must not leak');},now:Date.parse(stamp)+10000});assert.equal(s.get().archive.schools.duke.status,'stale');assert.equal(s.get().archive.schools.duke.checkedAt,stamp);assert.equal(s.get().archive.schools.duke.items.length,1);assert.equal(s.writes.length,1);await refreshPrivateCatalog(s.env,{fetcher:async()=>{throw Error('offline');},now:Date.parse(stamp)+20000});assert.equal(s.writes.length,1);});
test('successful empty feeds replace prior records, with one whole-document write',async()=>{const s=storage(seed());const fetcher=async url=>new Response(url==='https://player.example/'?'previous: "https://player.example/previous.xml"':url.endsWith('.xml')?'<main><previous_ev></previous_ev></main>':JSON.stringify({data:{sports:{sport:[]},events:{}}}));await refreshPrivateCatalog(s.env,{fetcher,now:Date.parse(stamp)+10000});assert.deepEqual(s.get().archive.schools.duke.items,[]);assert.equal(s.get().archive.schools.vt.status,'ready');assert.equal(s.writes.length,1);});
test('malformed catalog fails without leaking content or allowing reads to write',async()=>{const c=seed();c.live.duke.allowedOrigins=['https://foreign.example'];const s=storage(c);await assert.rejects(readPrivateCatalog(s.env),/^Error: Private catalog invalid$/);assert.equal(s.writes.length,0);});
test('unknown school including prototype properties has no target',()=>{assert.equal(findArchiveTarget(seed(),'__proto__','a'),null);});
test('oversized KV data rejected before JSON parsing',async()=>{await assert.rejects(readPrivateCatalog({STREAM_CATALOG:{get:async()=> 'x'.repeat(5_000_001)}}),/unavailable/);});
test('refresh keeps policy version and accepts explicitly allowed custom ports',async()=>{const c=seed();c.live.duke={url:'https://audio.example:8443/live',allowedOrigins:['https://audio.example:8443'],kind:'audio'};const s=storage(c);await readPrivateCatalog(s.env);await refreshPrivateCatalog(s.env,{fetcher:async()=>{throw Error('offline');},now:Date.parse(stamp)+10000});assert.equal(s.get().version,'1');});
test('malformed Duke document preserves last-known-good archive',async()=>{const s=storage(seed());await refreshPrivateCatalog(s.env,{fetcher:async url=>new Response(url==='https://player.example/'?'previous: "https://player.example/previous.xml"':'<main>unrecognized</main>'),now:Date.parse(stamp)+10000});assert.equal(s.get().archive.schools.duke.items.length,1);assert.equal(s.get().archive.schools.duke.checkedAt,stamp);});
test('private source field cannot accidentally publish a discovery URL',()=>{const c=seed();c.archive.schools.duke.source='https://private.example/discovery?token=secret';const body=JSON.stringify(publicArchiveCatalog(c,'https://gateway.example'));assert.ok(!body.includes('private.example'));assert.ok(body.includes('goduke.com'));});
test('archive redirect origins must be exact approved HTTPS origins for known schools',async()=>{const ok=seed();ok.archiveConfig.redirectOrigins={vt:['https://store.example'],duke:[]};const t=findArchiveTarget(await readPrivateCatalog(storage(ok).env),'duke','a');assert.deepEqual(t.allowedOrigins,['https://audio.example']);ok.archiveConfig.redirectOrigins.duke=['https://store.example','https://audio.example'];assert.deepEqual(findArchiveTarget(await readPrivateCatalog(storage(ok).env),'duke','a').allowedOrigins,['https://audio.example','https://store.example']);for(const bad of [['https://store.example/path'],['http://store.example'],'https://store.example',Array.from({length:17},(_,i)=>`https://s${i}.example`)]){const c=seed();c.archiveConfig.redirectOrigins={vt:bad};await assert.rejects(readPrivateCatalog(storage(c).env),/^Error: Private catalog invalid$/);}const unknown=seed();unknown.archiveConfig.redirectOrigins={other:['https://store.example']};await assert.rejects(readPrivateCatalog(storage(unknown).env),/^Error: Private catalog invalid$/);const proto=seed();proto.archiveConfig.redirectOrigins={__proto__:{duke:['https://store.example']}};assert.deepEqual(findArchiveTarget(await readPrivateCatalog(storage(proto).env),'duke','a').allowedOrigins,['https://audio.example']);});
